### PR TITLE
CSI-481_secret_stringData

### PR DESCRIPTION
**Pull request by igorgonibm**
Use stringData for storage address and usernames
No code change is needed. Updated only readme.

so instead of 
```
kind: Secret
apiVersion: v1
metadata:
   name: <VALUE-1>
   namespace: kube-system
 type: Opaque
 data:
   username: <VALUE-2 base64>        # Array username.
   password: <VALUE-3 base64>        # Array password.
   management_address: <VALUE-4 base64,VALUE-5 base64> # Array managment addresses

```

user can do this:
```
kind: Secret
apiVersion: v1
metadata:
   name: <VALUE-1>
   namespace: kube-system
 type: Opaque
 stringData:
   management_address: <VALUE-2,VALUE-3> # Array managment addresses
   username: <VALUE-4>                   # Array username.  
 data:
   password: <VALUE-5 base64>            # Array password.

```

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/96)

### CODE REVIEW

**Comment by shay-berman** [comment]
@igorgonibm did you tested it?
please check if there are other example secret files to update

**Comment by shay-berman** [comment]
@matt-levan  - since its not a code change - i would like to add this concept of secret - I asked Igor to investigate it and it looks like we can use stringData for the secret which is more human.
please see the PR and let me know what do you think.

**Comment by igorgonibm** [comment]
Tested of course
What I did is to find all places where string "ext4" is found and handled them. Do we want to add to all the examples "fstype: ext4" where fstype is not specified?

**Comment by shay-berman** [comment]
@igorgonibm  i think your last commet is for other PR, not this one

**Comment by igorgonibm** [comment]
Right. :)
Si,ilar answer. Searxhed for all places "management_address" is found.

**Comment by shay-berman** [comment]
thanks @igorgonibm  well done
I believe this PR improving the user experience.   And no real code change so please merge it to develop as part of v1.

**Comment by shay-berman** [comment]
Igor feel free to merge.

**Pull request merged**
