### PR TITLE
CSI-3122 creating 1.5.1

### PR DESCRIPTION
**Pull request by zingero**

### CODE REVIEW

**Review by oriyarde — DISMISSED** [review]
LGTM

**Review by ArbelNathan — APPROVED** [review]
LGTM

**Review by zingero — COMMENTED** [review]
I approve the second commit

**Review by ArbelNathan — APPROVED** [review]

**Review by zingero — COMMENTED** [review]
Approved

**Review by ArbelNathan — APPROVED** [review]

**Pull request merged**
