### PR TITLE
Improvment/refactor for generic scsi module

### PR DESCRIPTION
**Pull request by shay-berman**
**Description**
Make it easier to extend for FC support in addition to the existing iSCSI support.  @wangpww it should help you to implement FC because you will not have to duplicate things from the iscsi module to the new FC module. Instead you can just use the generic SCSI new module. (Detail below)
internal ticket CSI-391

**Implementation detail:**
by moving generic SCSI operations (that applicable for iscsi and FC) into a new interface `OsDeviceConnectivityHelperScsiGenericInterface` with the following APIs:
```
	RescanDevices(lunId int, arrayIdentifier string, sessionHosts []int) error
	FlushMultipathDevice(mpathDevice string) error
	RemovePhysicalDevice(sysDevices []string) error
```

The original code was inside the NewOsDeviceConnectivityIscsi struct.
So now the generic functions are out side NewOsDeviceConnectivityIscsi, and it just consumed by NewOsDeviceConnectivityIscsi.

Aligned the UT we already have for NewOsDeviceConnectivityIscsi.

**Note**
Also the `GetMpathDevice` can be moved to generic part but its not part of this PR (@wangpww  please do that as part of your FC PR).
We can make it generic based on the globs needed for iscsi vs fc:
	//      iSCSI -> /dev/disk/by-path/ip*-iscsi-<Array-WWN>-lun-<LUN-ID>
	//      FC    -> /dev/disk/by-path/pci-*-fc-<Array-WWN>-lun-<LUN-ID>

In addition - this PR also fix blocker issue with the new logger that was introduced in https://github.com/IBM/ibm-block-csi-driver/pull/51 (added it here since I hit the issue during testing).

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/52)

### CODE REVIEW

**Comment by igorgonibm** [comment]
___
*[node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go, line 54 at r1](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/52#-Ln7_mJx3vy9XygCSEzQ:-Ln7_mJx3vy9XygCSEzR:br1w9xc) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/03e5ad8ecad6dbde6b9466b6b638a4ea65dcfc70/node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go#L54)):*
> ```Go
> func (r OsDeviceConnectivityHelperScsiGeneric) RescanDevices(lunId int, arrayIdentifier string, sessionHosts []int) error {
> 	for _, hostNumber := range sessionHosts {
> ```

extract scan file path to global static variable

**Comment by igorgonibm** [comment]
___
*[node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go, line 84 at r1](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/52#-Ln7aE8PAS1xjm3yPxd8:-Ln7aE8PAS1xjm3yPxd9:b-aye88y) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/03e5ad8ecad6dbde6b9466b6b638a4ea65dcfc70/node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go#L84)):*
> ```Go
> 	// mpathdevice is dm-4 for example
> 	klog.V(5).Infof("Flushing mpath device : {%v}", mpathDevice)
> ```

extract to func which gets  mpatrhDevice and returns full device

**Comment by igorgonibm** [comment]
___
*[node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go, line 114 at r1](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/52#-Ln7cqdz2NdbZ8lI9zIS:-Ln7cqdz2NdbZ8lI9zIT:b7os03j) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/03e5ad8ecad6dbde6b9466b6b638a4ea65dcfc70/node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go#L114)):*
> ```Go
> func (r OsDeviceConnectivityHelperScsiGeneric) RemovePhysicalDevice(sysDevices []string) error {
> 	// sysDevices  = sdb, sda,...
> 	klog.V(5).Infof("Removing iscsi device : {%v}", sysDevices)
> ```

add the NOTE before method to me more BOLET

**Comment by igorgonibm** [comment]
___
*[node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go, line 125 at r1](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/52#-Ln7dAAd4vHL9_NrAtcp:-Ln7dAAd4vHL9_NrAtcq:bjmj3ni) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/03e5ad8ecad6dbde6b9466b6b638a4ea65dcfc70/node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go#L125)):*
> ```Go
> 			continue
> 		}
> ```

same with delete - extract to global constant

**Comment by igorgonibm** [comment]
___
*[node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go, line 142 at r1](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/52#-Ln7dLb7AhXdHvIywbQh:-Ln7dLb7AhXdHvIywbQi:b1di71o) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/03e5ad8ecad6dbde6b9466b6b638a4ea65dcfc70/node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go#L142)):*
> ```Go
> 		if _, err := f.WriteString("1"); err != nil {
> 			klog.Errorf("Error while writing to file : {%v}. error: {%v}", filename, err.Error())
> 			return err // TODO: maybe we need to just swallow the error and continnue??
> ```

still need TODO?

**Comment by igorgonibm** [comment]
___
*[node/pkg/driver/device_connectivity/device_connectivity_iscsi.go, line 70 at r1](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/52#-Ln7dUWe31J3ug_GdpjC:-Ln7dUWe31J3ug_GdpjD:bsatf8) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/03e5ad8ecad6dbde6b9466b6b638a4ea65dcfc70/node/pkg/driver/device_connectivity/device_connectivity_iscsi.go#L70)):*
> ```Go
> 	*/
> 	var devicePaths []string
> ```

need TODO?

**Comment by igorgonibm** [comment]
___
*[node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go, line 114 at r1](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/52#-Ln7cqdz2NdbZ8lI9zIS:-Ln8BAqx2vY-hdurFQ1w:b5j5bxf) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/03e5ad8ecad6dbde6b9466b6b638a4ea65dcfc70/node/pkg/driver/device_connectivity/device_connectivity_helper_scsigeneric.go#L114)):*
> BOLET
Just move the "NOTE" before the function

**Comment by shay-berman** [comment]
Tested manually(because CI still not valid) on k8s 1.13, works fine. Also added fix of the logger which block the develop(also tested).

**Pull request merged**
