### PR TITLE
CSI-2842 bump driver version to 1.6.0

### PR DESCRIPTION
**Pull request by zingero**
It's based on [this ](https://github.com/IBM/ibm-block-csi-driver/commit/eb4fe0d6afb46a26d74835c458302c839e9e6312)commit.

### CODE REVIEW

**Comment by ArbelNathan** [comment]
I know you haven't write it but didnt [this](https://github.com/IBM/ibm-block-csi-driver/blob/3b917371a2964496d771753d3b5b2e3b2ca9d380/controller/tests/controller_server/csi_controller_server_test.py#L1490) need to change too? and why it pass for the first place?

**Review by oriyarde — APPROVED** [review]
LGTM

**Review by ArbelNathan — APPROVED** [review]
LGTM

**Comment by zingero** [comment]
> I know you haven't write it but didnt [this](https://github.com/IBM/ibm-block-csi-driver/blob/3b917371a2964496d771753d3b5b2e3b2ca9d380/controller/tests/controller_server/csi_controller_server_test.py#L1490) need to change too? and why it pass for the first place?

Great question. Actually, it's the vendor version and in the test we can use any version we want. I changed the version to "some version" instead of "1.1.0" and it passes.

**Pull request merged**
