### PR TITLE
Feature/Add basic csi-node to the driver

### PR DESCRIPTION
**Pull request by shay-berman**
New basic csi node, that only implements Identity and basic node APIs.

We decided to develop the csi node side of things in GOLANG because we plan to use k8s mount lib and other csi libs in k8s community that which are in golang. (Note: the controller component was developed in python because all the IBM storage clients are in python like  pyxcli and pysvc). 

So a new directory `node` introduced for all the node golang related files:
node
├── cmd
│   └── main.go  
├── pkg
│   └── driver
│       ├── driver.go              
│       ├── identity.go           
│       ├── node.go           
│       ├── node_test.go
│       ├── version.go
│       └── version_test.go  
└── util
    ├── util.go
    └── util_test.go
│  └── main.go   ---> the command line of the csi node
go.mod
go.sum
Makefile

**main.go**
- This is the main file of the csi node. 
- Support flags [--csi-endpoint|--version].
- The Makefile build the node using this file and generate bin/ibm-block-csi-node-driver.

**driver.go**
- The Driver implements the CSI-identity interface and also hold the struct for CSI-Node interface.
- It has a Run() method that start to listen to the GRPC CSI endpoint (given as argument from the main.) and register the Identity and the node interfaces to this endpoint.
- Driver gets some info from the common/config.yaml. by default the binary search it under ./config.yaml, unless the environment `DRIVER_CONFIG_YML ENV` is defined.

**identity.go**
CSI Identity (for node) that implements all the Identity interfaces (Ready to go with this PR):
- `GetPluginInfo`: Get the driver name and version from common/config.yaml
- `GetPluginCapabilities`: Publish CONTROLLER_SERVICE capability. Note: Didn't take it from config.yaml file (we should consider refactor also in the controller).
- `Probe`: Do nothing just return OK.

**version.go**
- For supporting the --version flag.
- The details about GitCommit\BuildDate are automatically injected by the Makefile (using go build -X).
- The details about the GoVersion\Compiler\Platform are getting on the fly(run time).
- The driver version injected via the `common/config.yaml` file. (Just because I didn't want to break controller side that uses version from config.yaml)
```
./ibm-block-csi-node-driver --version
{
  "driverVersion": "1.0.0",
  "gitCommit": "0bbb233417ec73572b752f84da744806e656ea22",
  "buildDate": "",
  "goVersion": "go1.12.6",
  "compiler": "gc",
  "platform": "linux/amd64"
}

```

**Makefile**
Using makefile concept to build the CSI node by sing the following targets:
- ibm-block-csi-driver: go build the project and generate executable under bin/ibm-block-csi-node-driver
- gofmt: just apply gofmt on all the project.
- test:  Run go tests on the node directory.
- list:   Show all the targets

TODO: On different PR we will add more targets to create Docker image for CSI and also migrating CSI controller also to use Makefile party.

**node.go**
Adding stab for CSI node APIs:
- NodeStageVolume: Added with basic request verification, 
- NodeUnstageVolume: Same as NodeStageVolume.
- NodePublishVolume: Same as NodeStageVolume.
- NodeUnpublishVolume: Same as NodeStageVolume.

- NodeGetInfo: Raising Not-implemented(should be done in a different PR).

- NodeGetVolumeStats: Raise Not-implemented by design. Not part of this release.
- NodeExpandVolume: Raise Not-implemented by design. Not part of this release.
- NodeGetCapabilities: Done - check that we support NodeStage capability.

Note: Added full unit test for the above.

**utils.go** : 
- Generic functions like ParseEndpoint.

**go.mod \ go.sum**
CSI node is a golang module and it uses go modules for external dependencies.
The go.mod includes all the external dependancies and go.sum is auto generated during go build.

Other:
- logger; Uses `klog` for the logger to the CSI node. (Note: not sure how to use Debug message).  It also allow -v flag to the binary to set the log level. The log level in the code is 0 for all mandatory INFO, 4 for all regular debugging and 5 for tracing inside function get in and out.
- unit testing; go with standard golang testing (no more Ginkgo)

**TODO**
- Build Docker file for csi node using makefile and add it to CI pipeline
- Try to run csi Sanity on it

---
This change is [Reviewable](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/23)

### CODE REVIEW

**Comment by shay-berman** [comment]
Now added unit testing for the basic Node API, @olgashtivelman  please review.

**Comment by shay-berman** [comment]
Thanks for the review.
So the basic csi-node is ready.

Next week I will open new PR in order to continue the csi-node for:
1. Create csi-node dockerfile and one for unit testing
2. Add csi-node into the CI pipeline as follow: go tests -> gofmt checker -> gocoverage -> build image to artifactory.

**Comment by ranhrl** [comment]
___
*[node/pkg/driver/driver.go, line 111 at r3](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/23#-LicCfqD6rJZxcEqaAgX:-LicCfqD6rJZxcEqaAgY:b-gomsbr) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/c695a102baf256ee3c1047604adc1ab6c358a347/node/pkg/driver/driver.go#L111)):*
> ```Go
> 	if configYamlPath == "" {
> 		configYamlPath = DefualtConfigFile
> 		klog.V(4).Infof("Not found config file environment variable %s. Set default value %s.", EnvNameDriverConfFile, configYamlPath)
> ```

Please ask Rivka to review your messages.
Should we keep the messages in a common messages file? (also valid for Python). That's what we did with SC, and it helped a lot to review the messages.

**Comment by ranhrl** [comment]
___
*[node/pkg/driver/driver.go, line 118 at r3](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/23#-LicD0ii1sFQl2X_VOM0:-LicD0ii1sFQl2X_VOM1:b-n619qf) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/c695a102baf256ee3c1047604adc1ab6c358a347/node/pkg/driver/driver.go#L118)):*
> ```Go
> 	yamlFile, err := ioutil.ReadFile(configYamlPath)
> 	if err != nil {
> 		klog.Errorf("failed to read file %q: %v", yamlFile, err)
> ```

Again, your messages are not consistent with starting with a capital letter, finish with a dot etc. Rivka must review them.

**Comment by ranhrl** [comment]
___
*[node/pkg/driver/driver.go, line 101 at r3](https://reviewable.io/reviews/ibm/ibm-block-csi-driver/23#-LicCJuX8Ikouhjp-kgG:-LicCJuYBeki9VRrFzvh:b20me22) ([raw file](https://github.com/ibm/ibm-block-csi-driver/blob/c695a102baf256ee3c1047604adc1ab6c358a347/node/pkg/driver/driver.go#L101)):*
> ```Go
> 
> const (
> 	DefualtConfigFile     string = "config.yaml"
> ```

Defualt --> Default (typo)

**Pull request merged**
