### PR TITLE
CSI-3415: UG 2nd edition updates

### PR DESCRIPTION
**Pull request by rivkap**

### CODE REVIEW

**Review by oriyarde — DISMISSED** [review]
LGTM

**Review by ArbelNathan — APPROVED** [review]
LGTM

**Comment by rivkap** [comment]
> 
> 
> LGTM

**Comment by rivkap** [comment]
@oriyarde  please reapprove due to the latest changes from CSI-3415

**Review by oriyarde — APPROVED** [review]
LGTM

**Pull request merged**
