### PR TITLE
Wrong replication name is used (not suitable for idempotency check)

### PR DESCRIPTION
**Pull request by ELENAGER**
Signed-off-by: Elena Gershkovich <elenage@il.ibm.com>

### CODE REVIEW

**Review by ArbelNathan — APPROVED** [review]
LGTM

**Review by matancarmeli7 — COMMENTED** [review]
Can we add a unit test for this case? or it's covered already?

**Comment by ELENAGER** [comment]
Actually I've found this problem after writing and running the unit test (test_enable_ear_replication_idempotency_volume_has_another_policy_fails). So, test already exists

**Review by matancarmeli7 — APPROVED** [review]
LGTM

**Pull request merged**
