### PR TITLE
add example replication handle

### PR DESCRIPTION
**Pull request by oriyarde**

### CODE REVIEW

**Review by rivkap — COMMENTED** [review]
this is what I currently have in my documentation. please let me know if this needs to be changed.
if the user needs all of this information than it is good to have the information listed as such so it's clear. (referring specifically to the replicationHandle)

**Review by ArbelNathan — APPROVED** [review]
LGTM

**Review by rivkap — APPROVED** [review]
LGTM

**Review by ArbelNathan — APPROVED** [review]
LGTM

**Pull request merged**
